# Backbone
backbone: alexnet

# Transfer loss related
transfer_loss_weight: 1
transfer_loss: bnm

# Optimizer related
lr: 1e-2
weight_decay: 5e-4
lr_scheduler: True
lr_gamma: 0.0003
lr_decay: 0.75
momentum: 0.9

# Training related
batch_size: 128
pretrain: False
n_iter_per_epoch: 500
n_epoch: 40

# Others
seed: 2
num_workers: 1
