# Backbone
backbone: alexnet

# Transfer loss related
transfer_loss_weight: 0.5
transfer_loss: mmd

# Optimizer related
lr: 1e-3
weight_decay: 5e-4
lr_scheduler: True
lr_gamma: 0.0003
lr_decay: 0.75
momentum: 0.9

# Training related
batch_size: 64
pretrain: False
n_iter_per_epoch: 500
n_epoch: 40

# Others
seed: 1
num_workers: 4
